"""followers

Revision ID: 056107b6b3fb
Revises: 0725153af457
Create Date: 2019-05-22 11:13:44.856242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '056107b6b3fb'
down_revision = '0725153af457'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
